In [2]:
# Download reviews.txt and labels.txt from here: https://github.com/udacity/deep-learning/tree/master/sentiment-network

def pretty_print_review_and_label(i):
   print(labels[i] + "\t:\t" + reviews[i][:80] + "...")

g = open('reviews.txt','r') # What we know!
reviews = list(map(lambda x:x[:-1],g.readlines()))
g.close()

g = open('labels.txt','r') # What we WANT to know!
labels = list(map(lambda x:x[:-1].upper(),g.readlines()))
g.close()

In [41]:
import numpy as np

onehots = {}
onehots['cat'] = np.array([1,0,0,0])
onehots['the'] = np.array([0,1,0,0])
onehots['dog'] = np.array([0,0,1,0])
onehots['sat'] = np.array([0,0,0,1])

sentence = ['the','cat','sat']
x = onehots[sentence[0]] + \
    onehots[sentence[1]] + \
    onehots[sentence[2]]

input = list()
for word in sentence:
    input.append(onehots[word])
print('Plain:','\n', input, '\n')
input_np = np.array([np.array(input_i) for input_i in input])
print('Numpy Array:','\n', input_np, '\n')
#input_flat = input_np.flatten()
#print('Flatten: ', input_flat)
test_array = np.array([1,1,0,1])
weights_test = 0.2* np.random.random((len(onehots),4)) - 0.1 
print("Weights:",'\n', weights_test, '\n')

print('Embedded layer:','\n', np.sum(weights_test[test_array], axis=0 ))

Plain: 
 [array([0, 1, 0, 0]), array([1, 0, 0, 0]), array([0, 0, 0, 1])] 

Numpy Array: 
 [[0 1 0 0]
 [1 0 0 0]
 [0 0 0 1]] 

Weights: 
 [[-0.01818611 -0.07525092 -0.08364671 -0.04150304]
 [-0.03554806  0.00544011  0.05412751 -0.07615839]
 [ 0.07642483  0.06649604 -0.06632006  0.05392021]
 [ 0.05576549  0.08386976  0.05442845 -0.0855062 ]] 

Embedded layer: 
 [-0.12483028 -0.0589306   0.07873583 -0.26997822]


In [3]:
import sys

f = open('reviews.txt')
raw_reviews = f.readlines()
f.close()

f = open('labels.txt')
raw_labels = f.readlines()
f.close()
# create tokens by creating arrays of words by seperating them by spaces
tokens = list(map(lambda x:set(x.split(" ")),raw_reviews))

vocab = set()
for sent in tokens:
    for word in sent:
        if(len(word)>0):
            vocab.add(word)
vocab = list(vocab)

#Enumerate the words so neural net can perform computations, in NN terms One Hot Encode the data
word2index = {}
for i,word in enumerate(vocab):
    word2index[word]=i
print('The word "terrible" has the index:',word2index['terrible'])
input_dataset = list()
for sent in tokens:
    sent_indices = list()
    for word in sent:
        try:
            sent_indices.append(word2index[word])
        except:
            ""
    input_dataset.append(list(set(sent_indices)))
target_dataset = list()

for label in raw_labels:
    if label == 'positive\n':
        target_dataset.append(1)
    else:
        target_dataset.append(0)

The word "terrible" has the index: 58788


In [1]:
import numpy as np 
np.random.seed(1) 

def sigmoid(x): 
    return 1/(1 + np.exp(-x)) 

alpha, iterations = (0.01, 2) 
hidden_size = 100 

weights_0_1 = 0.2*np.random.random((len(vocab),hidden_size)) - 0.1 
weights_1_2 = 0.2*np.random.random((hidden_size,1)) - 0.1 

correct,total = (0,0)
for iter in range(iterations): 
    # train on first 24,000 
    for i in range(len(input_dataset)-1000): 
        x,y = (input_dataset[i],target_dataset[i]) 
        np_sum = np.sum(weights_0_1[x],axis=0)
        #print('sum:{} , size:{}'.format(np_sum, np_sum.shape))
        layer_1 = sigmoid(np_sum) #embed + sigmoid 
        #print('sigmoid: {}, shape: {}'.format(layer_1, layer_1.shape))
        layer_2 = sigmoid(np.dot(layer_1,weights_1_2)) # linear + softmax 
        layer_2_delta = layer_2 - y # compare pred with truth 
        layer_1_delta = layer_2_delta.dot(weights_1_2.T) #backprop 
        weights_0_1[x] -= layer_1_delta * alpha 
        weights_1_2 -= np.outer(layer_1,layer_2_delta) * alpha 

        if(np.abs(layer_2_delta) < 0.5): 
            correct += 1 
            total += 1 
            if(i % 10 == 9): 
                progress = str(i/float(len(input_dataset))) 
                sys.stdout.write('\rIter:' + str(iter)\
                                 +' Progress:' + progress[2:4]\
                                 +'.' + progress[4:6]\
                                 +'% Training Accuracy:'\
                                 + str(correct/float(total)) + '%') 
    print() 
correct,total = (0,0) 
for i in range(len(input_dataset)-1000,len(input_dataset)): 
    x = input_dataset[i] 
    y = target_dataset[i] 
    layer_1 = sigmoid(np.sum(weights_0_1[x],axis=0)) 
    layer_2 = sigmoid(np.dot(layer_1,weights_1_2)) 
    if(np.abs(layer_2 - y) < 0.5): 
        correct += 1 
    total += 1 
print("Test Accuracy:" + str(correct / float(total))) 

NameError: name 'vocab' is not defined

### 